name: pack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup folder
        run: |
          cd ${{ github.workspace }}
          sudo mkdir -p /packed/bin/x64/plugins/cyber_engine_tweaks/mods/
      - name: Copy files
        run: |
          sudo cp -r init.lua /packed/bin/x64/plugins/cyber_engine_tweaks/mods/
          sudo cp -r modules /packed/bin/x64/plugins/cyber_engine_tweaks/mods/
          sudo cp -r CPStyling /packed/bin/x64/plugins/cyber_engine_tweaks/mods/
          sudo cp -r config /packed/bin/x64/plugins/cyber_engine_tweaks/mods/
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
            name: gtaTravelLatest
            path: /packed/